debug: true

logging:
  level:
     org:
       springframework:
         security: DEBUG
         
# We need to setup different context root for the auth server so that we can store separate
# cookies for both the API gateway as well as the OAuth2 authorization server.
server:
  port: 8899
  contextPath: /authserver
  
appverse: 
  frontfacade:
    oauth2:
      jwt:
        jks:
          keystore: oauth-jwt-example-keystore.jks
          password: guessThis
          key: oauth-jwt-example
    rest:
      debug:
        requestdumper:
          enabled: true          

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  user:
    password: password  
    
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL

---

spring:
  profiles: docker
eureka:
# Register our microservices to Eureka using hostnames in a Docker environment will not work, they will all get 
# one and the same hostname. Instead we configure them to use its IP address during registration with Eureka.
  instance:
    preferIpAddress: true

  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/         